language: ruby
bundler_args: --without dev
script: bundle exec rake ci
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
gemfile:
  - Gemfile.minitest-2.2.2
  - Gemfile.minitest-2.3.0
  - Gemfile.minitest-3.0.0
  - Gemfile.rspec
